using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _12_HighlyDivisibleTriangular {
	/// <summary>
	/// From: https://projecteuler.net/problem=12
	/// The sequence of triangle numbers is generated by adding the natural numbers. 
	/// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
	/// The first ten terms would be:
	/// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
	/// </summary>
	class Program {
		static void Main(string[] args) {
		}
	}
}
